name: dry_run

on: pull_request

jobs:
  bot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    env:
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
      BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
      MASTODON_CLIENT_KEY: ${{ secrets.MASTODON_CLIENT_KEY }}
      MASTODON_CLIENT_SECRET: ${{ secrets.MASTODON_CLIENT_SECRET }}
      MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      SLOW_ZONE_BOT_SLACK_WEBHOOK_URL: ${{ secrets.SLOW_ZONE_BOT_SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run MBTA Slow Zone Bot in Dry Run mode
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run python3 slowzones.py --dry-run
